/**
 * Quick one-shot test: sends a quotation email (with a mock PDF attachment)
 * to the address passed as the first CLI arg, or falls back to RECEIVER_EMAIL.
 *
 *   node test_quotation_email.js bestsignatureautos@gmail.com
 *
 * Needs .env (or exported env vars): SMTP_EMAIL, SMTP_PASSWORD
 */
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '.env') });

const { sendQuotationEmail, verifySmtpConnection } = require('./utils/sendEmail');

const TO   = process.argv[2] || process.env.RECEIVER_EMAIL;
const NAME = 'Anvar (Test)';
const REF  = 'EQT-00099';

const mockItems = [
    { name: 'Rational iCombi Pro 6-1/1 Combi Oven', quantity: 1, price: 18500.00 },
    { name: 'Hoshizaki IM-65NE-HC Ice Machine',      quantity: 2, price: 4750.00 },
    { name: 'Vitamix Vita-Prep 3 Commercial Blender', quantity: 3, price: 1850.00 }
];

const mockTotals = {
    subtotal:        29600.00,
    discount_amount: 0,
    coupon_discount: 0,
    points_discount: 0,
    coupon_code:     null,
    points_used:     0,
    tax_amount:      1480.00   // 5 % VAT
};

const TOTAL = 31080.00;

// Build a tiny 1-page PDF in pure JS (no browser required) so the attachment
// slot is exercised. Uses only Node built-ins — no extra npm package needed.
function buildMinimalPdf(ref) {
    const body = [
        'BT',
        '/F1 14 Tf',
        '72 720 Td',
        `(Best Signature Auto Parts — Quotation ${ref}) Tj`,
        '/F1 11 Tf',
        '0 -24 Td',
        '(This is a test quotation PDF generated by the backend.) Tj',
        'ET'
    ].join('\n');

    const resources = '<< /Font << /F1 << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> >> >>';
    const mediaBox  = '[0 0 595 842]';

    const objs = [];
    const offsets = [];

    const push = (str) => { offsets.push(objs.reduce((a, o) => a + o.length, 0) + 9 /* %PDF\n */ ); objs.push(str); };

    push(`1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n`);
    push(`2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n`);
    push(`3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox ${mediaBox} /Contents 4 0 R /Resources ${resources} >>\nendobj\n`);
    const stream = `stream\n${body}\nendstream`;
    push(`4 0 obj\n<< /Length ${Buffer.byteLength(body) + 9} >>\n${stream}\nendobj\n`);

    let pdf = '%PDF-1.4\n';
    const base = pdf.length;
    const realOffsets = [];
    let pos = base;
    for (const o of objs) { realOffsets.push(pos); pos += o.length; }

    pdf += objs.join('');
    const xrefOffset = pdf.length;

    pdf += 'xref\n';
    pdf += `0 ${objs.length + 1}\n`;
    pdf += '0000000000 65535 f \n';
    for (const o of realOffsets) pdf += String(o).padStart(10, '0') + ' 00000 n \n';

    pdf += `trailer\n<< /Size ${objs.length + 1} /Root 1 0 R >>\n`;
    pdf += `startxref\n${xrefOffset}\n%%EOF\n`;

    return Buffer.from(pdf, 'utf8');
}

(async () => {
    if (!TO) {
        console.error('❌  Provide a recipient: node test_quotation_email.js <email>');
        process.exit(1);
    }
    if (!process.env.SMTP_EMAIL || !process.env.SMTP_PASSWORD) {
        console.error('❌  SMTP_EMAIL / SMTP_PASSWORD not set — add them to .env or export them');
        process.exit(1);
    }

    console.log('Verifying SMTP connection…');
    await verifySmtpConnection();

    const pdfBuffer = buildMinimalPdf(REF);
    console.log(`Sending quotation email to ${TO} (PDF: ${pdfBuffer.length} bytes)…`);

    await sendQuotationEmail(TO, NAME, REF, TOTAL, mockItems, 'en', mockTotals, pdfBuffer);

    console.log(`✅  Done — check ${TO}`);
    process.exit(0);
})().catch(e => { console.error('Fatal:', e.message); process.exit(1); });
